name: Tauri CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04  # 明确指定 LTS 版本
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \  # 更新后的包名
            libgtk-3-dev \
            libayatana-appindicator3-1 \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            librust-openssl-dev \
            libsoup2.4-dev \
            xvfb

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rust-src
          profile: minimal

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.1.8
          v8-flags: --max-old-space-size=4096

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cache/deno
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-${{ hashFiles('**/deno.lock', '**/Cargo.lock') }}

      - name: Install project dependencies
        run: |
          deno task --cwd src-tauri npm:install
          deno cache --lock=deno.lock --lock-write **/*.ts
          cargo generate-lockfile --manifest-path src-tauri/Cargo.toml

      - name: Build Tauri application
        env:
          DISPLAY: :99
          CARGO_TERM_COLOR: always
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 10
          deno task tauri build --verbose