name: Tauri CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            xvfb

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rust-src

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.1.8

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            src-tauri/target
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install project dependencies
        run: |
          deno task --cwd src-tauri npm:install
          deno cache --lock=deno.lock --lock-write **/*.ts

      - name: Build Tauri application
        env:
          XVFB_WRAPPER_TIMEOUT: 300
        run: |
          xvfb-run --auto-servernum deno task tauri build