name: Deno Tauri Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno-tauri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: '2.1.8'  # 使用你指定的 Deno 版本

    - name: Install GTK3, libsoup, and related dependencies
      run: |
        sudo apt update
        sudo apt install libwebkit2gtk-4.0-dev \
        build-essential \
       curl \
       wget \
        libssl-dev \
        libgtk-3-dev \
       libayatana-appindicator3-dev \
       librsvg2-dev



    - name: Set PKG_CONFIG_PATH
      run: |
        # Set the correct PKG_CONFIG_PATH for pkg-config to find .pc files
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
        # 如果你知道`.pc`文件的具体路径，可以在这里替换路径。

    - name: Install Deno dependencies
      run: deno install

    - name: Run Tauri Dev
      run: deno task tauri dev
