name: Deno Build Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.0-dev \
          build-essential \
          libgtk-3-dev \
          libayatana-appindicator3-dev

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: "1.43.x"  # 与您项目使用的版本保持一致

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust@v1
      with:
        rust-version: stable
        components: rustfmt, clippy

    - name: Cache Deno dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/deno
          deno.lock
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
        restore-keys: |
          ${{ runner.os }}-deno-

    - name: Initialize project
      run: |
        deno task init  # 假设您有初始化任务
        cd src-tauri
        cargo check

    - name: Build frontend
      run: deno task build  # 执行前端构建任务

    - name: Build Tauri
      run: |
        cd src-tauri
        cargo build --release