name: Deno Tauri Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno-tauri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 'v2.1.8'  # 使用合适的 Deno 版本

    - name: Install dependencies
      run: deno install

    - name: Run Tauri Dev
      run: deno task tauri dev
