name: Deno Tauri Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno-tauri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: '2.1.8'  # 使用你指定的 Deno 版本

    - name: Install GTK3, libsoup, and related dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libgtk-3-dev libsoup3.0-dev
        sudo apt install -y libjavascriptcoregtk-4.1-dev

    - name: Set PKG_CONFIG_PATH
      run: |
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
        # 在这里，我们将PKG_CONFIG_PATH设置为标准路径，这样pkg-config就能找到libsoup-3.0.pc

    - name: Install Deno dependencies
      run: deno install

    - name: Run Tauri Dev
      run: deno task tauri dev
